apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: coherence.coherence.oracle.com
spec:
  group: coherence.oracle.com
  names:
    categories:
    - coherence
    kind: Coherence
    listKind: CoherenceList
    plural: coherence
    shortNames:
    - coh
    singular: coherence
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  subresources:
    scale:
      labelSelectorPath: .status.selector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
